export const expertiseTags = [
  'Access Control',
  'Application Security',
  'Business Continuity',
  'Cloud Security',
  'Compliance',
  'Cryptography',
  'Data Protection',
  'DevSecOps',
  'Disaster Recovery',
  'Endpoint Security',
  'Forensic Analysis',
  'Identity Management',
  'Incident Response',
  'IoT Security',
  'Malware Analysis',
  'Mobile Security',
  'Network Security',
  'Penetration Testing',
  'Physical Security',
  'Reverse Engineering',
  'Risk Management',
  'Security Architecture',
  'Security Awareness',
  'Security Operations',
  'Threat Hunting',
  'Vulnerability Assessment',
  'Web Application Security',
  'Wireless Security',
  'Workstation Security',
];

export const platformSpecializationTags = [
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Kubernetes',
  'Docker',
  'Linux',
  'Windows',
  'macOS',
  'iOS',
  'Android',
  'Salesforce',
  'SAP',
  'Oracle',
  'VMware',
  'Cisco',
  'Juniper',
  'Palo Alto Networks',
  'Fortinet',
  'Check Point',
  'F5 Networks',
  'IBM',
  'Red Hat',
  'HPE',
  'Dell EMC',
  'NetApp',
  'Citrix',
  'Splunk',
  'ServiceNow',
  'Atlassian',
  'GitHub',
];
